import { describe, expect, test } from 'vitest'
import { render } from '@testing-library/react'
import {
  ASSET_CHIP,
  ASSET_FILL,
  BalanceBar,
  LIABILITY_CHIP,
  LIABILITY_FILL,
} from '@/components/balance-bar'
import type { BalanceTotals } from '@/lib/balance-sheet'

/**
 * The assets-versus-liabilities bar, asked for on 14 September.
 *
 * What is worth pinning is that the picture and the words agree, and that
 * neither can say something the figures do not.
 */
const totals = (assets: number, liabilities: number): BalanceTotals => ({
  assets,
  liabilities,
  net: assets - liabilities,
  closed: 0,
})

const bar = (container: HTMLElement) => ({
  assets: container.querySelector('[data-slot="bar-assets"]') as HTMLElement | null,
  liabilities: container.querySelector('[data-slot="bar-liabilities"]') as HTMLElement | null,
  picture: container.querySelector('[role="img"]') as HTMLElement | null,
})

describe('the balance bar', () => {
  test('draws each side in proportion to the two added together', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const { assets, liabilities } = bar(container)
    expect(assets!.style.flexBasis).toBe('75%')
    expect(liabilities!.style.flexBasis).toBe('25%')
  })

  /* Blue owned, red owed — asked for by name. Pinned because a swap would be
     invisible to every other assertion here and is the worst possible error
     this component could make. */
  test('blue is what is owned and red is what is owed', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const { assets, liabilities } = bar(container)
    expect(assets!.className).toContain(ASSET_FILL)
    expect(assets!.className).not.toMatch(/rose|red/)
    expect(liabilities!.className).toContain(LIABILITY_FILL)
    expect(liabilities!.className).not.toMatch(/sky|blue/)
  })

  /**
   * **The ramps point inward: palest at the bar's outer edges, strongest where
   * the two meet.** The join is the only thing on the bar that encodes the
   * ratio, so the paint is heaviest exactly there. Flipping either ramp would
   * put the pale ends together at the join and leave the boundary — the one
   * place a reader looks — as the faintest part of the picture.
   */
  test('each side is palest at its outer edge and strongest at the join', () => {
    // Assets run left to right: pale at the left edge, strong at the join.
    expect(ASSET_FILL).toContain('from-blue-100')
    expect(ASSET_FILL).toContain('to-blue-400')
    // Liabilities run the other way: strong at the join, pale at the right edge.
    expect(LIABILITY_FILL).toContain('from-red-400')
    expect(LIABILITY_FILL).toContain('to-red-100')
  })

  /**
   * The tints are the tiles' family, asked for on 14 September — 100 through
   * 400, not the 500-700 saturated steps this started with. Pinned as a RANGE
   * rather than by naming the stops twice: what matters is that nothing here
   * creeps back into the bright end of the palette.
   */
  test('both ramps stay in the soft end of the palette', () => {
    for (const fill of [ASSET_FILL, LIABILITY_FILL, ASSET_CHIP, LIABILITY_CHIP]) {
      const steps = [...fill.matchAll(/-(\d{3})\b/g)].map((m) => Number(m[1]))
      expect(steps.length).toBeGreaterThan(0)
      for (const step of steps) expect(step, fill).toBeLessThanOrEqual(400)
    }
  })

  /**
   * `bg-linear-to-r` is Tailwind v4's spelling; v3's `bg-gradient-to-r` is not
   * generated by this project's Tailwind and would leave a segment with no
   * background at all — a silent, invisible failure that no class assertion
   * above would catch, since both names are just strings here.
   */
  test('the gradient utility is the one this Tailwind generates', () => {
    for (const fill of [ASSET_FILL, LIABILITY_FILL]) {
      expect(fill).toContain('bg-linear-to-r')
      expect(fill).not.toContain('bg-gradient')
    }
  })

  /**
   * A chip takes its ramp's STRONG stop — at ten pixels square a gradient
   * starting at blue-100 is a pale smudge — but it has to be a stop that ramp
   * actually contains, or the legend explains a colour the bar never draws.
   */
  test('each legend chip is a colour its own segment is painted in', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const chips = Array.from(container.querySelectorAll('span[aria-hidden="true"]'))
    expect(chips).toHaveLength(2)
    expect(chips[0].className).toContain(ASSET_CHIP)
    expect(chips[1].className).toContain(LIABILITY_CHIP)

    // The chip's colour is one the ramp beside it is actually made of.
    expect(ASSET_FILL).toContain(ASSET_CHIP.replace('bg-', ''))
    expect(LIABILITY_FILL).toContain(LIABILITY_CHIP.replace('bg-', ''))
  })

  /**
   * With a fill this pale the bar's own extent needs an edge, or it appears to
   * start partway in: blue-100 measures 1.22:1 against the white card behind
   * it. The track's ring is what says where the bar begins and ends.
   */
  test('the track carries an edge, since the fill is too pale to give it one', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const picture = bar(container).picture!
    expect(picture.className).toContain('ring-1')
    expect(picture.className).toContain('ring-inset')
  })

  /**
   * **The join is drawn, not implied.** Blue-600 and red-600 measure 1.07:1
   * against each other — in greyscale, or to a viewer with no colour vision,
   * the bar would be one solid block. The white border sits inside the
   * segment's own box, so it marks the boundary without taking a pixel off
   * either proportion.
   */
  test('the two segments are separated by a drawn edge, not only by hue', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const { liabilities } = bar(container)
    expect(liabilities!.className).toContain('border-l-2')
    expect(liabilities!.className).toContain('border-white')
  })

  /**
   * The percentages are printed, so colour is never the only thing carrying
   * the reading (WCAG 1.4.1) — and they are the numbers the bar is drawing.
   */
  test('prints both percentages, and names both sides', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    expect(container.textContent).toContain('Assets')
    expect(container.textContent).toContain('75%')
    expect(container.textContent).toContain('Liabilities')
    expect(container.textContent).toContain('25%')
  })

  /** A screen reader gets the figures, not just "a chart" — the same treatment
   *  the investment ring takes. */
  test('the picture carries both figures for a screen reader', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const label = bar(container).picture!.getAttribute('aria-label')!
    expect(label).toContain('$750,000.00')
    expect(label).toContain('$250,000.00')
    expect(label).toContain('75%')
    expect(label).toContain('25%')
  })

  /**
   * **A group that owes nothing gets no red at all.** A minimum width applied
   * to a zero side would put six pixels of debt on a sheet that has none,
   * which is the one thing this bar must never say.
   */
  test('a side with nothing in it is not drawn', () => {
    const { container } = render(<BalanceBar totals={totals(500_000, 0)} />)
    const { assets, liabilities } = bar(container)
    expect(assets).toBeTruthy()
    expect(liabilities, 'a group with no debts has a red segment').toBeNull()
    expect(container.textContent).toContain('0%')
  })

  /* But a side that exists and is tiny IS drawn, with a floor under its width,
     rather than rounded out of sight. */
  test('a very small debt is still visible, and still labelled honestly', () => {
    const { container } = render(<BalanceBar totals={totals(1_000_000, 1_000)} />)
    const { liabilities } = bar(container)
    expect(liabilities).toBeTruthy()
    expect(liabilities!.className).toContain('min-w-')
    expect(container.textContent).toContain('<1%')
  })

  /** Nothing to divide is no bar: one colour, or none, says less than the
   *  space it would take. */
  test('an empty balance sheet renders nothing at all', () => {
    const { container } = render(<BalanceBar totals={totals(0, 0)} />)
    expect(container.innerHTML).toBe('')
  })

  /**
   * **It carries no chrome of its own.** It lives inside the net position card
   * now, between that card's label and its figure; a border, a ground or a
   * shadow here would draw a box inside a box.
   */
  test('it has no card of its own — it sits inside one', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const root = container.querySelector('[data-slot="balance-bar"]') as HTMLElement
    for (const chrome of ['border', 'shadow', 'bg-white', 'px-4', 'py-3', 'rounded-lg']) {
      expect(root.className, chrome).not.toContain(chrome)
    }
    // And it gives up width rather than forcing the row wider.
    expect(root.className).toContain('flex-1')
    expect(root.className).toContain('min-w-0')
  })

  /* The height is the one dimension a reader has specified twice — thick on
     sight, then 30% thinner — so a change to it should be deliberate. 28px
     less 30% is 19.6, and h-5 is the 20px step. */
  test('the bar is 20px tall', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const cls = bar(container).picture!.className
    expect(cls).toContain('h-5')
    expect(cls).not.toContain('h-7')
  })
})
