import { describe, expect, test } from 'vitest'
import { render } from '@testing-library/react'
import { ASSET_FILL, BalanceBar, LIABILITY_FILL } from '@/components/balance-bar'
import type { BalanceTotals } from '@/lib/balance-sheet'

/**
 * The assets-versus-liabilities bar, asked for on 14 September.
 *
 * What is worth pinning is that the picture and the words agree, and that
 * neither can say something the figures do not.
 */
const totals = (assets: number, liabilities: number): BalanceTotals => ({
  assets,
  liabilities,
  net: assets - liabilities,
  closed: 0,
})

const bar = (container: HTMLElement) => ({
  assets: container.querySelector('[data-slot="bar-assets"]') as HTMLElement | null,
  liabilities: container.querySelector('[data-slot="bar-liabilities"]') as HTMLElement | null,
  picture: container.querySelector('[role="img"]') as HTMLElement | null,
})

describe('the balance bar', () => {
  test('draws each side in proportion to the two added together', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const { assets, liabilities } = bar(container)
    expect(assets!.style.flexBasis).toBe('75%')
    expect(liabilities!.style.flexBasis).toBe('25%')
  })

  /* Blue owned, red owed — asked for by name. Pinned because a swap would be
     invisible to every other assertion here and is the worst possible error
     this component could make. */
  test('blue is what is owned and red is what is owed', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const { assets, liabilities } = bar(container)
    expect(assets!.className).toContain(ASSET_FILL)
    expect(assets!.className).not.toMatch(/rose|red/)
    expect(liabilities!.className).toContain(LIABILITY_FILL)
    expect(liabilities!.className).not.toMatch(/sky|blue/)
  })

  /**
   * **The ramps run light to dark, so the join is the darkest blue against the
   * lightest red** — 1.83:1, where two flat mid-tones measured 1.07:1 and the
   * bar read as one block in greyscale. Reversing either ramp would put dark
   * against dark and give that problem back, which no other assertion here
   * would notice.
   */
  test('each side ramps light to dark, so the two meet at their greatest difference', () => {
    expect(ASSET_FILL).toContain('from-sky-600')
    expect(ASSET_FILL).toContain('to-blue-700')
    expect(LIABILITY_FILL).toContain('from-rose-500')
    expect(LIABILITY_FILL).toContain('to-red-700')
  })

  /**
   * `bg-linear-to-r` is Tailwind v4's spelling; v3's `bg-gradient-to-r` is not
   * generated by this project's Tailwind and would leave a segment with no
   * background at all — a silent, invisible failure that no class assertion
   * above would catch, since both names are just strings here.
   */
  test('the gradient utility is the one this Tailwind generates', () => {
    for (const fill of [ASSET_FILL, LIABILITY_FILL]) {
      expect(fill).toContain('bg-linear-to-r')
      expect(fill).not.toContain('bg-gradient')
    }
  })

  /** The legend chip is painted from the same string as the segment it
   *  explains, so the two cannot drift into different blues. */
  test('each legend chip is the same paint as its segment', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const chips = Array.from(container.querySelectorAll('span[aria-hidden="true"]'))
    expect(chips).toHaveLength(2)
    expect(chips[0].className).toContain(ASSET_FILL)
    expect(chips[1].className).toContain(LIABILITY_FILL)
  })

  /**
   * **The join is drawn, not implied.** Blue-600 and red-600 measure 1.07:1
   * against each other — in greyscale, or to a viewer with no colour vision,
   * the bar would be one solid block. The white border sits inside the
   * segment's own box, so it marks the boundary without taking a pixel off
   * either proportion.
   */
  test('the two segments are separated by a drawn edge, not only by hue', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const { liabilities } = bar(container)
    expect(liabilities!.className).toContain('border-l-2')
    expect(liabilities!.className).toContain('border-white')
  })

  /**
   * The percentages are printed, so colour is never the only thing carrying
   * the reading (WCAG 1.4.1) — and they are the numbers the bar is drawing.
   */
  test('prints both percentages, and names both sides', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    expect(container.textContent).toContain('Assets')
    expect(container.textContent).toContain('75%')
    expect(container.textContent).toContain('Liabilities')
    expect(container.textContent).toContain('25%')
  })

  /** A screen reader gets the figures, not just "a chart" — the same treatment
   *  the investment ring takes. */
  test('the picture carries both figures for a screen reader', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    const label = bar(container).picture!.getAttribute('aria-label')!
    expect(label).toContain('$750,000.00')
    expect(label).toContain('$250,000.00')
    expect(label).toContain('75%')
    expect(label).toContain('25%')
  })

  /**
   * **A group that owes nothing gets no red at all.** A minimum width applied
   * to a zero side would put six pixels of debt on a sheet that has none,
   * which is the one thing this bar must never say.
   */
  test('a side with nothing in it is not drawn', () => {
    const { container } = render(<BalanceBar totals={totals(500_000, 0)} />)
    const { assets, liabilities } = bar(container)
    expect(assets).toBeTruthy()
    expect(liabilities, 'a group with no debts has a red segment').toBeNull()
    expect(container.textContent).toContain('0%')
  })

  /* But a side that exists and is tiny IS drawn, with a floor under its width,
     rather than rounded out of sight. */
  test('a very small debt is still visible, and still labelled honestly', () => {
    const { container } = render(<BalanceBar totals={totals(1_000_000, 1_000)} />)
    const { liabilities } = bar(container)
    expect(liabilities).toBeTruthy()
    expect(liabilities!.className).toContain('min-w-')
    expect(container.textContent).toContain('<1%')
  })

  /** Nothing to divide is no bar: one colour, or none, says less than the
   *  space it would take. */
  test('an empty balance sheet renders nothing at all', () => {
    const { container } = render(<BalanceBar totals={totals(0, 0)} />)
    expect(container.innerHTML).toBe('')
  })

  /* Thick, asked for by name. The height is the one dimension a reader
     specified, so a change to it should be deliberate. */
  test('the bar is thick', () => {
    const { container } = render(<BalanceBar totals={totals(750_000, 250_000)} />)
    expect(bar(container).picture!.className).toContain('h-7')
  })
})
